name: Deploy

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      db_service:
        image: postgres:latest
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
          run: ./gradlew build

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sample-employee-service" #Must be unique in Heroku
          heroku_email: "parameswaransankar@gmail.com"

